#!/bin/zsh
#
# This lets you quickly jump into a wp theme directory.
#
# Type:
#
#   th <tab>
#
# ...to autocomplete on all of your projects in the directories specified in
# `functions/_th`. Typically I'm using it like:
#
#    th wpsite<tab>
#

if [ ! -z "$1" ] && [ -s "$CODE/$1/htdocs/web/app/themes" ]; then
  COUNT=$(ls -l --color=never $CODE/$1/htdocs/web/app/themes/ | grep ^d | wc -l)
  if [ "$COUNT" =~ "1" ]; then;
    cd $(ls -d --color=never $CODE/$1/htdocs/web/app/themes/*|head -n 1)
  else
    cd $CODE/$1/htdocs/web/app/themes
  fi
else
  cd "$CODE/$1/htdocs/wp-content/themes"
fi
