apm install file-icons
apm install atom-project-manager
apm install atom-minimap
apm install merge-conflicts
apm install linter
apm install linter-csslint
apm install linter-htmlint
apm install linter-jslint
apm install linter-less
apm install linter-php
apm install emmet
apm install color-picker
apm install base16-ocean-dark-syntax-theme
apm install atom-material-ui
