apm install file-icons
apm install merge-conflicts
apm install linter
apm install linter-csslint
apm install linter-jslint
apm install linter-less
apm install linter-php
apm install emmet
apm install color-picker
apm install base16-ocean-dark-syntax-theme
apm install atom-material-ui
apm install pigments
apm install minimap
