#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/../osx

# Run Homebrew through the Brewfile
echo "› brew bundle"
brew bundle

cd "$(dirname $0)"/..
echo "› installs"
# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
